//定义用户登录 state 类型常量
export const USERLOGIN = "USERLOGIN";
export type USERLOGIN = typeof USERLOGIN;
export const RSA_PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCM/kBTkxNXglPURXg6fvM/ISVlwXeGdKWQGSkA2ol5ljEHC41oxg2LJ0Mr7tTLe0CJFA01U3FnGxt3fFDOprHsyvPslOWHDcTWW0rUqVxeUyamfVPJbsV3KZCDa9Y0TIJYIKFWL6f4FmuYjRAxwDhoAIPRbFQSNuC00dbKj798twIDAQAB";
